# Generated by Django 2.1.8 on 2019-08-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 9, 0, 14, 17, 315522), verbose_name='date published')),
                ('writer', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
    ]
