# Generated by Django 2.1.8 on 2019-08-09 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190809_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='youtubejobs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 22, 14, 31, 444596), verbose_name='date published'),
        ),
    ]
